export * from './sede.model';
export * from './fase.model';
export * from './grupo.model';
export * from './arbitro.model';
export * from './alineacion.model';
export * from './equipo.model';
export * from './jugador.model';
export * from './partido.model';
export * from './torneo.model';
